"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { X } from "lucide-react";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { getApiErrorMessage } from "@/lib/apiError";
import { useUpdateAdminUserStatusMutation } from "@/store/api/usersApi";
import type { AdminUserModerationRequest, UserModerationStatus } from "@/types/admin/user";

const schema = z.object({ reason: z.string().trim().min(3, "Enter at least 3 characters.").max(1000, "Reason must not exceed 1000 characters."), expiresAt: z.string() });
const labels: Record<UserModerationStatus, { title: string; text: string; success: string }> = { ACTIVE: { title: "Activate user", text: "This restores the user's moderation status to Active.", success: "User activated successfully." }, SUSPENDED: { title: "Suspend user", text: "This temporarily restricts this user according to backend moderation rules.", success: "User suspended successfully." }, BLOCKED: { title: "Block user", text: "Blocking is a stronger moderation action. Confirm that the account should be blocked.", success: "User blocked successfully." }, DEACTIVATED: { title: "Deactivate user", text: "This marks the account as deactivated.", success: "User deactivated successfully." } };
export function ModerationDialog({ userId, userName, status, onClose, onSuccess }: { userId: string; userName: string; status: UserModerationStatus; onClose: () => void; onSuccess: (message: string) => void }) { const [updateStatus, updateState] = useUpdateAdminUserStatusMutation(); const form = useForm<{ reason: string; expiresAt: string }>({ resolver: zodResolver(schema), defaultValues: { reason: "", expiresAt: "" } }); useEffect(() => { const listener = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", listener); return () => window.removeEventListener("keydown", listener); }, [onClose]); async function submit(values: { reason: string; expiresAt: string }) { const body: AdminUserModerationRequest = { status, reason: values.reason }; if (values.expiresAt) body.expiresAt = new Date(values.expiresAt).toISOString(); try { await updateStatus({ userId, body }).unwrap(); onSuccess(labels[status].success); } catch { } } const details = labels[status]; return <div className="fixed inset-0 z-50 grid place-items-center bg-navy/40 p-4" role="presentation"><section role="dialog" aria-modal="true" aria-labelledby="moderation-title" className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-start justify-between"><div><h2 id="moderation-title" className="text-xl font-bold text-navy">{details.title}</h2><p className="mt-1 text-sm text-slate-500">{userName}</p></div><button type="button" aria-label="Close dialog" onClick={onClose} className="rounded-lg p-2 text-slate-500"><X className="size-5" /></button></div><p className="mt-4 text-sm text-slate-600">{details.text}</p><form onSubmit={form.handleSubmit(submit)} className="mt-5 space-y-4"><label className="block text-sm font-medium text-navy">Reason<textarea {...form.register("reason")} rows={4} className="mt-2 w-full rounded-lg border border-line p-3 text-sm focus:border-accent" />{form.formState.errors.reason && <span className="mt-1 block text-xs text-red-600">{form.formState.errors.reason.message}</span>}</label>{status === "SUSPENDED" && <label className="block text-sm font-medium text-navy">Expiry <span className="font-normal text-slate-400">(optional)</span><input type="datetime-local" {...form.register("expiresAt")} className="mt-2 block h-10 rounded-lg border border-line px-3 text-sm" /></label>}{updateState.isError && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{getApiErrorMessage(updateState.error)}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-line px-4 py-2 text-sm font-semibold text-slate-600">Cancel</button><button disabled={updateState.isLoading} type="submit" className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{updateState.isLoading ? "Saving…" : "Confirm"}</button></div></form></section></div>; }
