"use client";

import { useState } from "react";
import { useGetDashboardAnalyticsQuery } from "@/store/api/dashboardApi";
import type { DashboardAnalyticsRange, DashboardTrendPoint } from "@/types/admin/dashboard";
import { getApiErrorMessage } from "@/lib/apiError";

const ranges: { label: string; value: DashboardAnalyticsRange }[] = [{ label: "7 Days", value: "7D" }, { label: "30 Days", value: "30D" }, { label: "90 Days", value: "90D" }, { label: "1 Year", value: "1Y" }];
function TrendBars({ label, points, color }: { label: string; points: DashboardTrendPoint[]; color: string }) { const maximum = Math.max(...points.map((point) => point.count), 1); return <div><div className="mb-3 flex items-center justify-between"><p className="text-sm font-medium text-navy">{label}</p><span className="text-xs text-slate-400">{points.reduce((total, point) => total + point.count, 0)} total</span></div>{points.length ? <div className="flex h-28 items-end gap-1 border-b border-line pb-1">{points.map((point) => <div key={point.date} title={`${point.date}: ${point.count}`} className={`min-w-1 flex-1 rounded-t ${color}`} style={{ height: `${Math.max((point.count / maximum) * 100, 4)}%` }} />)}</div> : <p className="rounded-xl bg-surface p-4 text-sm text-slate-500">No activity in this range.</p>}</div>; }
export function DashboardAnalytics() { const [range, setRange] = useState<DashboardAnalyticsRange>("30D"); const analytics = useGetDashboardAnalyticsQuery(range); return <section className="rounded-2xl border border-line bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-semibold text-navy">Platform analytics</h3><p className="mt-1 text-sm text-slate-500">Activity recorded in {analytics.data?.timeZone ?? "the configured timezone"}.</p></div><div className="flex flex-wrap gap-1 rounded-lg bg-surface p-1">{ranges.map((item) => <button type="button" key={item.value} onClick={() => setRange(item.value)} className={`rounded-md px-2.5 py-1.5 text-xs font-medium ${range === item.value ? "bg-white text-brand shadow-sm" : "text-slate-500"}`}>{item.label}</button>)}</div></div>{analytics.isLoading ? <div className="mt-7 h-64 animate-pulse rounded-xl bg-surface" /> : analytics.isError ? <div className="mt-7 rounded-xl bg-red-50 p-4 text-sm text-red-700">{getApiErrorMessage(analytics.error, "Unable to load analytics.")} <button type="button" className="ml-2 font-semibold underline" onClick={() => analytics.refetch()}>Try Again</button></div> : analytics.data ? <div className="mt-7 grid gap-6"><TrendBars label="User registrations" points={analytics.data.userRegistrations} color="bg-brand" /><TrendBars label="Matches created" points={analytics.data.matchesCreated} color="bg-emerald-500" /><TrendBars label="Tournaments created" points={analytics.data.tournamentsCreated} color="bg-amber-500" /></div> : null}</section>; }
